spring.application.name=pc-sales-system

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PCShopDB;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123qwe123

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080
